name: pyenv
channels:
  - anaconda
  - conda-forge
dependencies:
  - python=3.10
  - pip>=24.0
  - numpy>=1.24.1
  - pandas>=1.1.5
  - python-dateutil>=2.8.2
  - pytz>=2021.3
  - scipy>=1.5.3
  - six>=1.15.0
  - joblib>=1.2.0
  - pip:
      - jupyterlab>=3.2.9
      - scikit-learn>=0.0
      - xenonfs>=0.5.2
      - Sentence-Transformers>=2.2.2
